name: qrpc-web build and deploy 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: cp qrpc.esm.js ./docs
  #     - name: Deploy
  #       env:
  #         ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  #         PUBLISH_BRANCH: master
  #         PUBLISH_DIR: ./docs
  #         SCRIPT_MODE: true
  #       run: |
  #         wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
  #         bash ./entrypoint.sh


