name: qrpc-web build and deploy 

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: yarn install
    - run: yarn build
    - run: yarn publish
    - name: deploy to github-pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.zzf03680147 }}
        BRANCH: gh-pages
        FOLDER: test
        BUILD_SCRIPT: cp qrpc.esm.js ./test


